site_name: Sodero Documents
# site_url: https://docs.sodero.io/
site_url: https://kate-sodero.github.io/test/
theme:
  name: material
  favicon: assets/tab_icon.svg
  custom_dir: docs/overrides
  font:
    text: "Inter"
    code: "JetBrains Mono"
  palette:
    - scheme: slate
      primary: black
      accent: white
  features:
    - navigation.path
    - navigation.sections
    - navigation.tracking
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share
    
extra:
  version:
    provider: mike
  comments:
    provider: giscus
    options:
      repo: Sodero-labs/docs
      repo_id: R_kgDOQiK7fQ  
      category: Q&A   
      category_id: DIC_kwDOQiK7fc4C3JkV
      mapping: pathname
      strict: 0
      reactions_enabled: 1
      emit_metadata: 0
      input_position: bottom
      theme: dark
      lang: en

extra_css:
  - styles/layout.css
  - styles/color.css
  - styles/font.css
extra_javascript:
  - javascripts/mathjax.js
  - javascripts/select-all.js
  - javascripts/nav-state.js
  - javascripts/version.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Get Started:
    - Overview: index.md
    - Sodero Ecosystem: get_started/sodero_ecosystem/index.md
  - Hardware Setup:
    - Stellar Series:
      - Stellar X: hardware_setup/stellar_series/stellar_x/index.md
  # - Software Module:
  #   - Stellar Designer:
  #     - Overview: software_module/stellar_designer/what_is_stellarx/index.md
  #     - Robot Structure: software_module/stellar_designer/robot_structure/index.md
  #     - Robot System Parameters: software_module/stellar_designer/robot_system_parameters/index.md
  #     - Actuator Mapping: software_module/stellar_designer/actuator_mapping/index.md
  #     - Virtual Verification: software_module/stellar_designer/virtual_verification/index.md
  #   - Stellar Motion Studio:
  #     - Overview: software_module/stellar_motion_studio/what_is_stellarx/index.md
  - Tutorials:
    - Stellar Designer:
      - Introduction: tutorials/stellar_designer/introduction/index.md
      - Create New Robot:
        - Robot Structure: tutorials/stellar_designer/robot_structure/index.md
        - Robot System Parameters: tutorials/stellar_designer/configure_system_parameters/index.md
        - Actuator Mapping: tutorials/stellar_designer/map_actuators/index.md
        - Virtual Verification: tutorials/stellar_designer/verify_configuration/index.md
      - Start from Templates: tutorials/stellar_designer/start_from_templates/index.md
    - Stellar Motion Studio:
      - About Stellar Motion Studio: tutorials/stellar_motion_studio/about_stellar_motion_studio/index.md
      - Home: tutorials/stellar_motion_studio/home/index.md
      - Tool: tutorials/stellar_motion_studio/tool/index.md
      - Pose: tutorials/stellar_motion_studio/pose/index.md
      - Motion: tutorials/stellar_motion_studio/motion/index.md
  - Virtual Simulation:
    - Virtual Control Overview: virtual_simulation/virtual_control_overview/index.md
    - NVIDIA Isaac Sim:
      - Introduction: virtual_simulation/introduction/index.md
      - Extension Installation: virtual_simulation/extension_installation/index.md
      - Robot Setup: virtual_simulation/robot_setup/index.md
  - Manual:
    - Remote Control:
      - Understanding Remote Control: manual/remote_control/understanding_remote_control/index.md
    - Stellar Designer:
      - Robot Structure: manual/stellar_designer/robot_structure/index.md
      - Robot System Parameters: manual/stellar_designer/robot_system_parameters/index.md
      - Actuator Mapping: manual/stellar_designer/actuator_mapping/index.md
    - APIS: manual/apis/index.md
  - ChangeLog: CHANGELOG.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - glightbox
  - search
  - llmstxt:
      full_output: llms-full.txt
      sections:
        Tutorials - Stellar Designer:
          - stellarx/tutorials/stellar_designer/**/*.md
        Tutorials - Stellar Motion Studio:
          - stellarx/tutorials/stellar_motion_studio/**/*.md
        Tutorials - Simulation & Virtual Control:
          - stellarx/tutorials/simulation/**/*.md
        User Guide:
          - stellarx/user_guide/**/*.md
