name: publish site
on:
  push:
    branches:
      - 'v[0-9].*' # v1.0, v2.0 등 버전 이름으로 된 브랜치들
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy with mike
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME}
          
          # git 설정
          git config --global user.name "kate-sodero"
          git config --global user.email "본인이메일"

          # 1. 원격의 최신 상태를 가져오기 (충돌 방지)
          git fetch origin gh-pages --depth=1 || true

          # 2. --force 옵션을 추가하여 강제로 푸시합니다.
          # 이 옵션이 있으면 'rejected' 에러를 무시하고 덮어씁니다.
          mike deploy --push --force --update-aliases $BRANCH_NAME latest
          
          # 3. 기본 페이지 설정
          mike set-default --push --force latest