name: publish site
on:
  push:
    branches:
      - 'v[0-9].*' # v1.0, v2.0 등 버전 이름으로 된 브랜치들
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy with mike
        run: |
          # 현재 푸시된 브랜치 이름을 버전명으로 사용 (예: v1.0 브랜치면 v1.0으로 배포)
          BRANCH_NAME=${GITHUB_REF_NAME}
          
          # 해당 브랜치의 소스코드를 빌드해서 gh-pages의 해당 폴더로 보냄
          mike deploy --push --update-aliases $BRANCH_NAME $BRANCH_NAME
          
          # 필요하다면 가장 최신 브랜치를 기본 페이지로 설정
          mike set-default --push $BRANCH_NAME